AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  carbonemissioncar:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: carbon_emission_car
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::663325156950:role/SAR_Lambda_FullAccess'
      Runtime: python3.8
      Timeout: 3
